### ISSUE TITLE
Create Inspection mechanism for entities

### ISSUE THREAD

**Issue by costea32** [TestMonkeys/jEntityTest#1]
The users should be able to mark the entity with comparison annotations either at field or getter level. Either one should be caught by jEntityTest in order to be able to create the ComparisonModel, with preference for the field.

**Comment by monofrei** [comment]
Starting working on this.

**Comment by monofrei** [comment]
Costea "Permission to TestMonkeys/jEntityTest.git denied to monofrei."
Could you help me with this?

**Comment by costea32** [comment]
Done

**Comment by monofrei** [comment]
Worked. Thank you.

**Comment by costea32** [comment]
Closing as the functionality desired was implemented, another issue will be raised for refactoring and edge case analysis and fix.
